// examples/example-vue-sdk-2.x-no-osdk/src/Home.vue
<script setup lang="ts">
import Header from "./components/Header.vue";
import NextSteps from "./components/NextSteps.vue";
</script>

<template>
  <div class="home">
    <Header />
    <NextSteps />
  </div>
</template>

<style scoped>
.home {
  display: flex;
  flex-direction: column;
  gap: 60px;
  width: 800px;
}
</style>

// examples/example-react-sdk-2.x-no-osdk/src/Home.tsx
import React from "react";
import css from "./Home.module.css";
import Header from "./components/Header";
import NextSteps from "./components/NextSteps";

function Home(): React.ReactElement {
  return (
    <div className={css.home}>
      <Header />
      <NextSteps />
    </div>
  );
}

export default Home;
