// examples/example-vue-sdk-2.x/src/components/Osdk.vue
<script setup lang="ts"></script>

<template>
  <div class="osdk">
    <div>
      <span>OSDK: </span>
      <span class="tag">@osdk/e2e.generated.catchall</span>
    </div>
    <a
      href="https://fake.palantirfoundry.com/workspace/developer-console/app/ri.third-party-applications.main.application.fake/docs/guide/loading-data?language=typescript"
      class="docs"
      target="_blank"
      rel="noreferrer"
    >
      <img src="/book.svg" width="16" height="16" alt="Book icon" />
      <span>View documentation</span>
    </a>
  </div>
</template>

<style scoped>
.osdk {
  align-self: baseline;
  display: flex;
  justify-content: space-between;
  width: 800px;
}

.tag {
  border: 1px solid #11141826;
  border-radius: 2px;
  padding: 2px 4px;
}

.docs {
  align-items: center;
  border-radius: 2px;
  color: #1c2127;
  display: flex;
  gap: 8px;
  height: 30px;
  justify-content: center;
  padding: 0 5px;
  text-decoration: none;
}

.docs:hover {
  background: #8f99a826;
}
</style>

// examples/example-react-public-sdk-2.x/src/components/Osdk.tsx
import { AnchorButton, Icon, Tag } from "@blueprintjs/core";
import React from "react";
import css from "./Osdk.module.css";

const DOCUMENTATION_URL =
  "https://fake.palantirfoundry.com/workspace/developer-console/app/ri.third-party-applications.main.application.fake/docs/guide/loading-data?language=typescript";

function Osdk(): React.ReactElement {
  return (
    <div className={css.osdk}>
      <div>
        <span>OSDK: </span>
        <Tag minimal={true}>@osdk/e2e.generated.catchall</Tag>
      </div>
      <AnchorButton
        href={DOCUMENTATION_URL}
        target="_blank"
        rel="noreferrer"
        variant="minimal"
        icon={<Icon icon="book" aria-label="Book icon"></Icon>}
      >
        View documentation
      </AnchorButton>
    </div>
  );
}

export default Osdk;
