// examples/example-react-2.0/src/Home.tsx
import { Ontology } from "@osdk/e2e.generated.catchall";
import client from "./client";
import css from "./Home.module.css";
import Layout from "./Layout";

function Home() {
  const objectApiNames = Object.keys(Ontology.objects);
  const actionApiNames = Object.keys(client(Ontology.actions));
  const queryApiNames = Object.keys(client(Ontology.queries));

  return (
    <Layout>
      <h1>@osdk/e2e.generated.1.1.x</h1>
      <p>
        Welcome to your Ontology SDK! Try using any of the following methods
        now.
      </p>
      <div className={css.methods}>
        <div>
          <h2>Objects ({objectApiNames.length})</h2>
          {objectApiNames.map((objectApiName) => (
            <pre key={objectApiName}>
              client.ontology.objects.{objectApiName}
            </pre>
          ))}
        </div>
        <div>
          <h2>Actions ({actionApiNames.length})</h2>
          {actionApiNames.map((actionApiName) => (
            <pre key={actionApiName}>
              client.ontology.actions.{actionApiName}
            </pre>
          ))}
        </div>
        <div>
          <h2>Queries ({queryApiNames.length})</h2>
          {queryApiNames.map((queryApiName) => (
            <pre key={queryApiName}>
              client.ontology.queries.{queryApiName}
            </pre>
          ))}
        </div>
      </div>
    </Layout>
  );
}

export default Home;

// examples/example-vue-sdk-1.x/src/Home.vue
<script setup lang="ts">
import client from "./client";

const objectApiNames = Object.keys(client.ontology.objects);
const actionApiNames = Object.keys(client.ontology.actions);
const queryApiNames = Object.keys(client.ontology.queries);
</script>

<template>
  <h1>@osdk/e2e.generated.1.1.x</h1>
  <p>
    Welcome to your Ontology SDK! Try using any of the following methods now.
  </p>
  <div class="methods">
    <div>
      <h2>Objects ({{ objectApiNames.length }})</h2>
      <pre v-for="objectApiName in objectApiNames" key="objectApiName">client.ontology.objects.{{ objectApiName }}</pre>
    </div>
    <div>
      <h2>Actions ({{ actionApiNames.length }})</h2>
      <pre v-for="actionApiName in actionApiNames" key="actionApiName">client.ontology.actions.{{ actionApiName }}</pre>
    </div>
    <div>
      <h2>Queries ({{ queryApiNames.length }})</h2>
      <pre v-for="queryApiName in queryApiNames" key="queryApiName">client.ontology.queries.{{ queryApiName }}</pre>
    </div>
  </div>
</template>

<style scoped>
.methods {
  padding: 2em;
  gap: 2em;
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
}
</style>
