// packages/create-app.template.vue/templates/src/AuthCallback.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import client from "./client";
import { useRouter } from "vue-router";

const router = useRouter();

const error = ref<string>();

onMounted(() => {
  client.auth
    .signIn()
    .then(() => router.replace("/"))
    .catch((e: unknown) => {
      error.value = (e as Error).message;
    });
});
</script>

<template>
  <div>{{ error != null ? error : "Authenticating…" }}</div>
</template>

// packages/e2e.sandbox.oauth.public.react-router/src/AuthCallback.tsx
import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { publicOauthClient } from "./client.js";

/**
 * Component to render at `/auth/callback`
 * This calls signIn() again to save the token, and then navigates the user back to the home page.
 */
function AuthCallback() {
  const navigate = useNavigate();
  const [error, setError] = useState<string | undefined>(undefined);

  useEffect(() => {
    publicOauthClient()
      .then(() => navigate("/", { replace: true }))
      .catch((e: unknown) => setError((e as Error).message ?? e));
  }, [navigate]);

  return <div>{error != null ? error : "Authenticating…"}</div>;
}

export default AuthCallback;
