// packages/create-app.template.vue/templates/src/Layout.vue
<template>
  <div>
    <a
      href="https://www.palantir.com/docs/foundry/ontology-sdk/overview/"
      target="_blank"
      rel="noreferrer"
    >
      <img src="/palantir.svg" class="logo" alt="Palantir logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank" rel="noreferrer">
      <img src="/vue.svg" class="logo" alt="Vue logo" />
    </a>
  </div>
  <router-view />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
</style>

// examples/example-react-sdk-2.x/src/Layout.tsx
import palantirLogo from "/palantir.svg";
import reactLogo from "/react.svg";
import React from "react";
import css from "./Layout.module.css";

interface LayoutProps {
  children?: React.ReactNode;
}

function Layout({ children }: LayoutProps) {
  return (
    <>
      <div>
        <a
          href="https://www.palantir.com/docs/foundry/ontology-sdk/overview/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <img src={palantirLogo} className={css.logo} alt="Palantir logo" />
        </a>
        <a href="https://react.dev" target="_blank" rel="noopener noreferrer">
          <img src={reactLogo} className={css.logo} alt="React logo" />
        </a>
      </div>
      {children}
    </>
  );
}

export default Layout;
