// packages/create-app/src/__snapshots__/expected-template-vue/src/Login.vue
<script setup lang="ts">
import { onUpdated, ref } from "vue";
import client from "./client";
import { useRouter } from "vue-router";

const router = useRouter();

const isLoggingIn = ref(false);
const error = ref<string>();

const login = async () => {
  isLoggingIn.value = true;
  try {
    await client.auth.signIn();
  } catch (e: unknown) {
    error.value = (e as Error).message;
  } finally {
    isLoggingIn.value = false;
  }
};

onUpdated(() => {
  console.log(client.auth.token);
  // If the token exists but a user tries to load /login, redirect to the home page instead
  if (client.auth.token != null) {
    router.replace("/");
  }
});
</script>

<template>
  <h1>Ontology SDK</h1>
  <button @click="login">
    {{ isLoggingIn ? "Logging in…" : "Log in " }}
  </button>
  <div v-if="error">Unable to log in: {{ error }}</div>
</template>

// packages/create-app/templates/template-react/src/Login.tsx
import { useCallback, useState } from "react";
import { Navigate } from "react-router-dom";
import client from "./client";
import Layout from "./Layout";

function Login() {
  const [isLoggingIn, setIsLoggingIn] = useState(false);
  const [error, setError] = useState<string | undefined>(undefined);
  const token = client.auth.token;

  const handleLogin = useCallback(async () => {
    setIsLoggingIn(true);
    try {
      // Initiate the OAuth flow, which will redirect the user to log into Foundry
      // Once the login has completed, the user will be redirected back to the route defined via the
      // FOUNDRY_REDIRECT_URL variable in .env.development
      await client.auth.signIn();
    } catch (e: unknown) {
      console.error(e);
      setError((e as Error).message ?? e);
    } finally {
      setIsLoggingIn(false);
    }
  }, []);

  // If the token exists but a user tries to load /login, redirect to the home page instead
  if (token != null) {
    return <Navigate to="/" replace={true} />;
  }

  return (
    <Layout>
      <h1>Ontology SDK</h1>
      <button onClick={handleLogin}>
        {isLoggingIn ? "Logging in…" : "Log in "}
      </button>
      {error && <div>Unable to log in: {error}</div>}
    </Layout>
  );
}

export default Login;
