// examples/example-react-sdk-2.x/src/components/Header.tsx
import React from "react";
import css from "./Header.module.css";

function Header(): React.ReactElement {
  return (
    <div className={css.header}>
      <div className={css.logos}>
        <a
          href="https://www.palantir.com/docs/foundry/ontology-sdk/overview/"
          target="_blank"
          rel="noreferrer"
        >
          <img src="/palantir.svg" className={css.logo} alt="Palantir logo" />
        </a>
        <a href="https://react.dev" target="_blank" rel="noreferrer">
          <img src="/react.svg" className={css.logo} alt="React logo" />
        </a>
      </div>
      <h2 className={css.heading}>
        Build your React application with Foundry!
      </h2>
    </div>
  );
}

export default Header;

// packages/create-app.template.vue.v2/templates/src/components/Header.vue
<script setup lang="ts"></script>

<template>
  <div class="header">
    <div class="logos">
      <a
        href="https://www.palantir.com/docs/foundry/ontology-sdk/overview/"
        target="_blank"
        rel="noreferrer"
      >
        <img src="/palantir.svg" class="logo" alt="Palantir logo" />
      </a>
      <a href="https://react.dev" target="_blank" rel="noreferrer">
        <img src="/vue.svg" class="logo" alt="React logo" />
      </a>
    </div>
    <h2 class="heading">Build your React application with Foundry!</h2>
  </div>
</template>

<style scoped>
.header {
  align-items: center;
  display: flex;
  flex-direction: column;
  gap: 40px;
}

.logos {
  display: flex;
  gap: 32px;
}

.logo {
  height: 48px;
  transition: filter 300ms;
  will-change: filter;
}

.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
</style>
