// examples/example-osdk-react-sdk-2.x-no-osdk/src/components/NextSteps.tsx
import cube from "/cube.svg";
import tag from "/tag.svg";

import React from "react";
import css from "./NextSteps.module.css";

const STEPS: INextStep[] = [
  {
    icon: cube,
    title: "Configure your Ontology and Platform SDKs",
    subtitle: (
      <span>
        Use the Ontology SDK to interact with your Ontology and the Platform SDK
        to access Foundry APIs. Configure your SDKs from the{" "}
        <strong>Ontology SDK</strong> and <strong>Platform SDK</strong> tabs in
        Developer Console.
      </span>
    ),
  },
  {
    icon: tag,
    title: "Deploy your application",
    subtitle: (
      <span>
        To deploy a new version of your application, tag a new version of your
        repository or use the command line to run{" "}
        <code className={css.code}>npx @osdk/cli@latest site deploy</code>.{" "}
        <a
          className={css.learnMore}
          href="https://www.npmjs.com/package/@osdk/cli"
          target="_blank"
          rel="noreferrer"
        >
          Learn more.
        </a>
      </span>
    ),
  },
];

export function NextSteps(): React.ReactElement {
  return (
    <div className={css.nextSteps}>
      <h5 className={css.nextStepsHeader}>Next steps</h5>
      {STEPS.map((step) => (
        <NextStep
          key={step.title}
          icon={step.icon}
          title={step.title}
          subtitle={step.subtitle}
        />
      ))}
    </div>
  );
}

interface INextStep {
  icon: string;
  title: string;
  subtitle: React.ReactElement;
}

function NextStep({
  icon,
  title,
  subtitle,
}: INextStep): React.ReactElement {
  return (
    <div className={css.nextStep}>
      <img src={icon} className={css.icon} alt={icon} />
      <div className={css.nextStepContent}>
        <h6 className={css.title}>{title}</h6>
        <div className={css.subtitle}>{subtitle}</div>
      </div>
    </div>
  );
}

// packages/create-app.template.vue.v2/templates/src/components/NextSteps.vue
<script setup lang="ts">
interface INextStep {
  icon: string;
  title: string;
  subtitle: string;
}

const STEPS: INextStep[] = [
{{^if osdkPackage}}
  {
    icon: "cube",
    title: "Configure your Ontology and Platform SDKs",
    subtitle:
      "Use the Ontology SDK to interact with your Ontology and the Platform SDK to access Foundry APIs. Configure your SDKs from the Ontology SDK and Platform SDK tabs in Developer Console.",
  },
{{^if applicationUrl}}
{{/if}}
  {
    icon: "cloud",
    title: "Request a subdomain to host your application with Foundry",
    subtitle:
      "Register a subdomain for your website in the Website hosting tab in Developer Console. Then, add this subdomain to your redirect URLs on the OAuth & scopes tab and update your .env.production file.",
  },
{{/if}}
  {
    icon: "tag",
    title: "Deploy your application",
    subtitle:
      "Generate a new tag version of your repository to deploy a new version of your applicaiton.",
  },
];
</script>

<template>
  <div class="next-steps">
    <h5 class="next-steps-header">Next steps</h5>
    <div v-for="step in STEPS" :key="step.title" class="next-step">
      <img :src="`/${step.icon}.svg`" class="icon" :alt="step.icon" />
      <div class="next-step-content">
        <h6 class="title">{{ step.title }}</h6>
        <div class="subtitle">{{ step.subtitle }}</div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.next-steps {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.next-steps-header {
  align-self: baseline;
  font-size: 16px;
  font-weight: 600;
}

.next-step {
  border: 1px solid #11141826;
  border-radius: 4px;
  display: flex;
  gap: 15px;
  padding: 16px;
}

.next-step-content {
  display: flex;
  flex-direction: column;
  gap: 4px;
  text-align: left;
}

.title {
  font-weight: 600;
}

.subtitle {
  color: #5f6b7c;
}

.icon {
  height: 34px;
}
</style>
