// packages/create-app.template.react.beta/templates/src/components/osdk-Osdk.tsx
import React from "react";
import css from "./Osdk.module.css";

function Osdk(): React.ReactElement {
  return (
    <div className={css.osdk}>
      <div>
        <span>OSDK: </span>
        <span className={css.tag}>@template-test-3/sdk</span>
      </div>
      <a
        href="{{foundryUrl}}/workspace/developer-console/app/{{application}}/docs/guide/loading-data?language=typescript"
        className={css.docs}
        target="_blank"
      >
        <img src="/book.svg" width={16} height={16}></img>
        <span>View documentation</span>
      </a>
    </div>
  );
}

export default Osdk;

// packages/create-app.template.vue.v2/templates/src/components/osdk-Osdk.vue
<script setup lang="ts"></script>

<template>
  <div class="osdk">
    <div>
      <span>OSDK: </span>
      <span class="tag">@template-test-3/sdk</span>
    </div>
    <a
      href="{{foundryUrl}}/workspace/developer-console/app/{{application}}/docs/guide/loading-data?language=typescript"
      class="docs"
      target="_blank"
    >
      <img src="/book.svg" width="16" height="16" />
      <span>View documentation</span>
    </a>
  </div>
</template>

<style scoped>
.osdk {
  align-self: baseline;
  display: flex;
  justify-content: space-between;
  width: 800px;
}

.tag {
  border: 1px solid #11141826;
  border-radius: 2px;
  padding: 2px 4px;
}

.docs {
  align-items: center;
  border-radius: 2px;
  color: #1c2127;
  display: flex;
  gap: 8px;
  height: 30px;
  justify-content: center;
  padding: 0 5px;
  text-decoration: none;
}

.docs:hover {
  background: #8f99a826;
}
</style>
